In [1]:
import pandas as pd

In [6]:
mdel_pgain = pd.read_csv('survival_results/survival_mdel_pgain_tcga_glioma.csv', index_col = 0)
mdel_pgain

          log_rank       p_value long_survival
A1BG     42.650605  6.544420e-11           low
ACPT      1.055175  3.043182e-01           low
ACTN4    83.950780  5.072475e-20           low
ADCK4    50.435214  1.231643e-12           low
AKT1S1   26.921534  2.118849e-07           low
...            ...           ...           ...
ZSCAN18   0.000060  9.938236e-01           low
ZSCAN22  80.052062  3.646734e-19           low
ZSCAN4    0.031743  8.585936e-01          high
ZSCAN5A  86.505074  1.393792e-20           low
ZSCAN5B  30.626908  3.127264e-08          high

[798 rows x 3 columns]

In [7]:
# keep rows with p-value < 0.01
mdel_pgain = mdel_pgain[mdel_pgain['p_value'] < 0.01]

# keep rows with long_survival == low
mdel_pgain = mdel_pgain[mdel_pgain['long_survival'] == 'low']

In [9]:
mdel_pgain_list = mdel_pgain.index.tolist()

In [10]:
# save the list to a file
with open('survival_mdel_pgain_tcga_glioma_list.txt', 'w') as f:
    for item in mdel_pgain_list:
        f.write("%s\n" % item)

---

In [28]:
genes = pd.read_csv('survival_mdel_pgain_tcga_glioma_list.txt', sep = ": ", index_col = 0, header = None)

/tmp/ipykernel_48739/1520010143.py:1: ParserWarning: Falling back to the 'python' engine because the 'c' engine does not support regex separators (separators > 1 char and different from '\s+' are interpreted as regex); you can avoid this warning by specifying engine='python'.
  genes = pd.read_csv('survival_mdel_pgain_tcga_glioma_list.txt', sep = ": ", index_col = 0, header = None)

In [29]:
genes

                 1
0
A1BG     Secretory
ACTN4    Cytosolic
ADCK4           모름
AKT1S1   Cytosolic
AKT2     Cytosolic
...            ...
ZNF841          모름
ZNF880          모름
ZSCAN1          모름
ZSCAN22         모름
ZSCAN5A         모름

[375 rows x 1 columns]

In [30]:
genes_secretory = genes[genes[1] == 'Secretory']
genes_surface = genes[genes[1] == 'Surface']
genes_cytosolic = genes[genes[1] == 'Cytosolic']
genes_unclear = genes[genes[1] == '모름']

In [34]:
genes_surface

                1
0
AXL       Surface
BCAM      Surface
C5AR1     Surface
CD33      Surface
CD37      Surface
CEACAM1   Surface
CEACAM3   Surface
CEACAM4   Surface
EMP3      Surface
FCAR      Surface
FCGRT     Surface
FFAR2     Surface
FPR1      Surface
FPR2      Surface
FPR3      Surface
FXYD3     Surface
FXYD5     Surface
GIPR      Surface
GPR4      Surface
GPR77     Surface
HCST      Surface
KCNC3     Surface
KCNK6     Surface
KCNN4     Surface
KIRREL2   Surface
LAIR1     Surface
LILRA2    Surface
LILRA5    Surface
LILRA6    Surface
LILRB1    Surface
LILRB2    Surface
LILRB3    Surface
LILRB4    Surface
MYADM     Surface
NCR1      Surface
OSCAR     Surface
PLAUR     Surface
PTGIR     Surface
PVR       Surface
PVRL2     Surface
RGS9BP    Surface
SCN1B     Surface
SIGLEC10  Surface
SIGLEC11  Surface
SIGLEC14  Surface
SIGLEC16  Surface
SIGLEC5   Surface
SIGLEC7   Surface
SIGLEC9   Surface
SIGLECP3  Surface
SLC1A5    Surface
SLC7A9    Surface
TMEM190   Surface
TRPM4     Surface
TYROBP    Surface
VSIG10L   Surface
VSTM1     Surface